### ISSUE TITLE
nefunguje automatizace

### ISSUE THREAD

**Issue by Re4DeR** [jvyoralek/homeassistant-config#1]
https://github.com/jvyoralek/homeassistant-config/blob/master/home-assistant/configuration.yaml ze vsech tri pomocnych automatizacich je treba vyhodit     hide_entity: true  (depreacated v 112 verzi)

**Comment by jvyoralek** [comment]
Díky za upozornění. Příslušné položky z automatizací odstraněny a přesunuto do samostatného automations.yaml souboru.
